version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Henry@786
      - MYSQL_ROOT_HOST='127.0.0.1'
    volumes:
      - /home/yogen/Desktop/mysqldb:/var/lib/mysql
      # - /var/www/html/mysqld:/var/lib/mysql
    networks:
      - myapp-network
  app:
    image: crawler_app:1.0.5
    depends_on:
      - mysqldb
    restart: unless-stopped
    container_name: reasonlabs
    ports:
      - 5002:4000
    command: bash -c "npx sequelize-cli db:create && npx sequelize-cli db:migrate && node app.js"
    # command: bash -c "node app.js"
    stdin_open: true
    tty: true
    networks:
      - myapp-network
volumes: 
  db:
networks:
  myapp-network:
    driver: bridge